### ISSUE TITLE
Build failure at generating javadoc with frank-runner

### ISSUE THREAD

**Issue by Matthbo** [wearefrank/ladybug#207]
I'm trying to run the ladybug using the instructions in the [readme#How to change and test Ladybug](https://github.com/wearefrank/ladybug?tab=readme-ov-file#how-to-change-and-test-ladybug).

For some weird reason it can't generate the javadoc correctly during the build process when using frank-runner/specials/ibis-ladybug

Output of restart.bat: 
[frank-runner_restart.bat_output.txt](https://github.com/wearefrank/ladybug/files/13686894/frank-runner_restart.bat_output.txt)

ladybug, ladybug-frontend, ladybug-test-webapp are freshly cloned and the frank-runner is up-to-date with master at the date of writing this issue (15-12-23)

**Comment by Matthbo** [comment]
Turns out this is because the frank-runner tries to build with jdk 17 which makes the javadoc fail to be generated (because of an html5 error).
Maybe a jdk check should be done to make sure other devs know it needs jdk 8 to build properly.
And it could be useful to update the frank-runner to use jdk 8 instead of 17

**Comment by jkosternl** [comment]
Currently, this project is not updated from Java 8 to Java 11 or higher yet. So, your findings are likely correct.

**Comment by jacodg** [comment]
Easiest way around it (as I told Matthijs and a few others) is to copy the build-example.properties to build.properties and enable maven.skip.javadoc=true. It's also handy to enable other skip properties, from the README.md:

To speed up the build copy build-exmaple.properties in this folder to build.properties and enable the relevant properties as describes in the comments in this file.

But indeed we should fix the Javadoc (which is on my to do since I've noted that my Frank!Runner change to use Java 17 by default started to give these warnings) or change the Ladybug build to use Java 8 (again).

**Comment by jkosternl** [comment]
@jacodg, Matt also worked on a PR to make it better already. #208 Perhaps you can check that out and merge it, if it is a good idea. 
I also think that it might be a good idea to configure the master code to skip Javadoc by default, since this seems to be broken currently, until it is fixed again.

**Comment by jacodg** [comment]
Ah, yes, now looked at it, thanks.

In CI/CD (Jenkins) JDK 8 is still being used so the CI is still doing a nice check on the Javadoc

**Comment by jacodg** [comment]
Als warnings have been fixed with #208 and https://github.com/wearefrank/ladybug/commit/b79837ca529e20d8212119c4bd30d3b05e2cb5e7
