### ISSUE TITLE
Ladybug GitHub Actions succeeded even though copyright notices were not OK.

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug#236]

**Comment by mhdirkse** [comment]
We observed this here:

![Image](https://github.com/wearefrank/ladybug/assets/6784732/51284348-49fe-491e-8589-5697ed61a894)

**Comment by mhdirkse** [comment]
@MarkvdVorst suggested that the ladybug backend GitHub test may not test the Maven build of the backend. We know that the ladybug backend tests trigger ladybug-frontend, but that may be the only thing the test does.

**Comment by MarkvdVorst** [comment]
It would be nice to have a dedicated action for backend testing instead of only having a yaml file for ladybug-frontend tests.
I'm guessing the ladybug-frontend yaml also takes the backend into account somehow, but skips the tests copyright and/or unit tests as it did not give me any failed tests earlier when I submitted a PR with wrong copyright year.

**Comment by MarkvdVorst** [comment]
nevermind. the skip copyright is still present in this

**Comment by mhdirkse** [comment]
Ik denk dat de Ladybug backend op Jenkins wordt getest, zie https://jenkins.frankframework.org/job/ladybug-ci/job/ladybug/. Daar wordt de volledige Maven build gedaan, dus zonder opties om stappen over te slaan.
